---
title: "FB Test With Multiple Verb Types (Stress Test)"
author: "Sean Trott, Cameron Jones, Pam Rivière"
date: "April 24, 2025"
#output:
  #pdf_document: 
    #   fig_caption: yes
    #   keep_md: yes
    #   keep_tex: yes
    #   html_document:
output:
  html_document:
    keep_md: yes
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 300, fig.format = "png")

```

```{r include=FALSE}
library(tidyverse)
library(lmtest)
library(forcats)
library(broom)
library(lme4)
library(viridis)
library(ggridges)
library(lmerTest)
library(ggrepel)
library(ggcorrplot)
library(dplyr)
library(ggplot2)

```

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/NLMs/epistemology/dev_tom/src/analysis")

# Grab data for false belief task
directory_path <- "../../data/processed/fb_local_multi_verb/"
csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_all_models <- bind_rows(csv_list) %>%
  mutate(model_shorthand = str_to_title(model_shorthand))
nrow(df_all_models)

# Create a column with numeric versions of the tokens seen for that step, using 
# the Olmo file naming convention
df_all_models$tokens_seen_numeric <- as.numeric(sub("B", "", df_all_models$tokens_seen)) * 1e9

df_all_models = df_all_models %>%
  # filter(stage == "stage1") %>%
  mutate(model_id = paste(stage, "step", "-", step)) %>%
  mutate(tokens_seen_numeric_mod = tokens_seen_numeric + 1)

## NOTE: Pythia model data contains a "main" checkpoint/step that appears as a NaN in the `step` column
## must change this to the actual value of the final step, 143000
df_all_models$step[is.na(df_all_models$step)] <- 143000 #hard-coded the final step 

# sort df columns by model name and step value
df_all_models <- df_all_models %>%
  arrange(model_shorthand, step)  # arrange in ascending order

metadata <- read_csv("../../data/raw/metadata_models.csv")
# merge the metadata with the fb task df
df_all_models_verb_task <- df_all_models %>% left_join(metadata, by = "model_shorthand")

tokens_seen_pythia <- read_csv("../../data/raw/pythia_tokens_seen.csv")
# merge stepwise tokens data for Pythia models
df_all_models_verb_task <- df_all_models_verb_task %>%
  left_join(tokens_seen_pythia %>% select(model_shorthand, step, tokens_seen_from_df1 = tokens_seen_numeric), 
            by = c("model_shorthand", "step")) %>%
  mutate(tokens_seen_numeric = coalesce(tokens_seen_numeric, tokens_seen_from_df1)) %>%
  select(-tokens_seen_from_df1) %>%
  mutate(tokens_seen_numeric_mod = tokens_seen_numeric + 1)


df_all_models_verb_task = df_all_models_verb_task %>%
  mutate(model_family = case_when(
    model_shorthand %in% c("Pythia 14m", "Pythia 1b", 
                           "Pythia 6.9b", "Pythia 12b") ~ "Pythia",
    model_shorthand %in% c("Olmo 2 1b", "Olmo 2 7b", "Olmo 2 13b") ~ "Olmo 2",
  ))
```

## Analysis

### Final step

```{r density_final_step}
df_all_models_verb_task %>%
  group_by(model_path) %>%
  mutate(max_tokens = max(tokens_seen_numeric)) %>%
  filter(tokens_seen_numeric == max_tokens) %>%
  ggplot(aes(x = log_odds,
           fill = condition,
           y = verb_type)) +
  geom_density_ridges(color = NA, alpha = 0.7, scale = 0.9) +
  labs(x = "Log Odds",
       y = "Verb Type",
       fill = "Condition") +
  theme_minimal(base_size = 13) +
  geom_vline(xintercept = 0, linetype = "dotted") +
  theme(text = element_text(size = 15),
        legend.position = "bottom",
        legend.box = "vertical",          # stack the shape + color legends
        legend.text = element_text(size = 11),   # shrink legend text
        legend.key.width = unit(0.8, "cm")) +
  scale_fill_manual(values = viridisLite::viridis(2, option = "mako", 
                                                  begin = 0.8, end = 0.15)) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  facet_wrap(~reorder(model_shorthand, n_params_approx), nrow=2)


library(dplyr)
library(forcats)
library(emmeans)

df_plot <- df_all_models_verb_task %>%
  group_by(model_path) %>%
  mutate(max_tokens = max(tokens_seen_numeric)) %>%
  filter(tokens_seen_numeric == max_tokens) %>%
  ungroup() %>%
  arrange(verb_type, verb) %>%
  mutate(
    verb = factor(verb, levels = unique(verb))
  )

ggplot(df_plot,
       aes(x = log_odds,
           fill = condition,
           y = verb)) +
  geom_density_ridges(color = NA, alpha = 0.7, scale = 0.9) +
  labs(x = "Log Odds",
       y = "Verb Type",
       fill = "Condition") +
  theme_minimal(base_size = 13) +
  geom_vline(xintercept = 0, linetype = "dotted") +
  theme(
    text = element_text(size = 15),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.text = element_text(size = 11),
    legend.key.width = unit(0.8, "cm")
  ) +
  scale_fill_manual(values = viridisLite::viridis(2, option = "mako", 
                                                  begin = 0.8, end = 0.15)) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  facet_wrap(~reorder(model_shorthand, n_params_approx))


df_final = df_all_models_verb_task %>%
  group_by(model_path) %>%
  mutate(max_tokens = max(tokens_seen_numeric)) %>%
  filter(tokens_seen_numeric == max_tokens) 



### Need to update
mod_final = lmer(data = df_final,
                 log_odds ~ verb_type * condition + 
                   recent_mention + first_mention +
                   # (1 | model_shorthand) + 
                   (1 | verb) +
                   (1 | start),
                 REML = FALSE)

summary(mod_final)



### Show overall
df_summary <- df_final %>%
  group_by(verb_type, condition) %>%
  summarize(
    mean_log_odds = mean(log_odds, na.rm = TRUE),
    se = sd(log_odds, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

ggplot(df_summary,
       aes(x = verb_type,
           y = mean_log_odds,
           color = condition,
           group = condition)) +
  geom_point(size = 3,
             position = position_dodge(width = 0.2)) +
  geom_line(position = position_dodge(width = 0.2)) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  scale_color_manual(values = viridisLite::viridis(2, option = "mako", 
                                                  begin = 0.8, end = 0.15)) +
  geom_errorbar(aes(ymin = mean_log_odds - 1.96 * se,
                    ymax = mean_log_odds + 1.96 * se),
                width = 0.1,
                position = position_dodge(width = 0.2)) +
  labs(
    x = "Verb Type",
    y = "Mean Log Odds",
    color = "Condition"
  ) +
  theme_minimal() +
  theme(
    text = element_text(size = 15),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.text = element_text(size = 11),
    legend.key.width = unit(0.8, "cm")
  ) 

```

#### Explanatory power

```{r final_step_model_comps}



library(lme4)
library(dplyr)
library(ggplot2)

### Remove verb as random factor b/c otherwise it'll soak up too much variance
### That would be attributed to verb_type
mods <- list(

  null =
    lmer(
      log_odds ~
        (1 | start),
      data = df_final,
      REML = FALSE
    ),

  condition =
    lmer(
      log_odds ~
        condition +
        (1 | start),
      data = df_final,
      REML = FALSE
    ),

  verb_type =
    lmer(
      log_odds ~
        verb_type +
        (1 | start),
      data = df_final,
      REML = FALSE
    ),

  mentions =
    lmer(
      log_odds ~
        recent_mention +
        first_mention +
        (1 | start),
      data = df_final,
      REML = FALSE
    ),

  additive =
    lmer(
      log_odds ~
        verb_type +
        condition +
        recent_mention +
        first_mention +
        (1 | start),
      data = df_final,
      REML = FALSE
    ),

  interaction =
    lmer(
      log_odds ~
        verb_type * condition +
        recent_mention +
        first_mention +
        (1 | start),
      data = df_final,
      REML = FALSE
    )
)

aic_df <- tibble(
  model = names(mods),
  AIC = sapply(mods, AIC)
) %>%
  mutate(
    delta_AIC = AIC - min(AIC)
  ) %>%
  arrange(delta_AIC)

aic_df

ggplot(aic_df,
       aes(x = reorder(model, delta_AIC),
           y = delta_AIC,
           fill = model)) +
  geom_col(width = 0.7) +
  coord_flip() +
  geom_hline(yintercept = c(2, 6, 10),
             linetype = "dashed",
             color = "grey60") +
  labs(
    x = NULL,
    y = expression(Delta*AIC)
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")
### test
summary(lm(data = df_final,
                 log_odds ~ verb_type))
summary(lm(data = df_final,
                 log_odds ~ condition))

```

### Over time

```{r accuracy}
### Mark correct answers
df_all_models_verb_task = df_all_models_verb_task %>%
  mutate(correct = case_when(
    condition == "False Belief" & log_odds > 0 ~ TRUE,
    condition == "True Belief" & log_odds <= 0 ~ TRUE,
    TRUE ~ FALSE  # all other cases are incorrect
  ))


df_summ_verbs <- df_all_models_verb_task %>%
  group_by(model_path, model_shorthand,
           step, tokens_seen_numeric, model_family, stage, condition, knowledge_cue, verb_type) %>%
  summarise(mean_accuracy = mean(correct),
            mean_lo = mean(log_odds)) %>%
  mutate(tokens_seen_numeric_mod = tokens_seen_numeric + 1)

df_summ_verbs %>%
  select(model_shorthand, mean_accuracy)
mean(df_all_models_verb_task$correct)

df_summ_verbs %>%
  ungroup() %>%
  arrange(desc(mean_accuracy)) %>%
  select(model_shorthand, mean_accuracy, step, stage, condition, knowledge_cue, verb_type) %>%
  head(5)


df_summ_verbs %>%
  ggplot(aes(x = tokens_seen_numeric,
             y = mean_accuracy,
             color = condition,
             shape = knowledge_cue)) +
  geom_line() +
  geom_hline(yintercept = .5, linetype = "dotted") +
  geom_point(size = 2, alpha = .4) +
  scale_x_log10() +
  scale_color_manual(values = viridisLite::viridis(2, option = "mako", 
                                                  begin = 0.8, end = 0.15)) +
  labs(title = "False Belief Task Accuracy",
       y = "Accuracy",
       x = "Number of Tokens Seen (log scale)") + 
  theme_minimal() +
  facet_wrap(~verb_type)

  

df_summ_verbs %>%
  ggplot(aes(x = tokens_seen_numeric,
             y = mean_lo,
             color = condition,
             shape = knowledge_cue)) +
  geom_line() +
  geom_point(size = 2, alpha = .5) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  scale_x_log10() +
  scale_color_manual(values = viridisLite::viridis(2, option = "mako", 
                                                  begin = 0.8, end = 0.15)) +
  labs(title = "False Belief Task Log Odds (Start v. End)",
       y = "Log Odds",
       x = "Number of Tokens Seen (log scale)") +
  facet_wrap(~verb_type) + 
  theme_minimal() +
  theme(legend.position = "bottom")



```


### Track explanatory power

```{r}
fit_aic_by_step <- function(dat) {

  m_null <- lmer(log_odds ~  (1 | start),
                 data = dat, REML = FALSE)

  m_cond <- lmer(log_odds ~ condition +
                   (1 | start),
                 data = dat, REML = FALSE)

  m_verb <- lmer(log_odds ~ verb_type +
                   (1 | start),
                 data = dat, REML = FALSE)

  tibble(
    AIC_null = AIC(m_null),
    AIC_condition = AIC(m_cond),
    AIC_verb_type = AIC(m_verb)
  ) %>%
    mutate(
      step = unique(dat$step),
      tokens = unique(dat$tokens_seen_numeric),
      delta_cond = AIC_condition - AIC_null,
      delta_verb = AIC_verb_type - AIC_null
    )
}

aic_time <- df_all_models_verb_task %>%
  group_by(step, tokens_seen_numeric) %>%
  group_modify(~fit_aic_by_step(.x)) %>%
  ungroup()

aic_long <- aic_time %>%
  select(step, tokens_seen_numeric, delta_cond, delta_verb) %>%
  tidyr::pivot_longer(
    cols = c(delta_cond, delta_verb),
    names_to = "predictor",
    values_to = "delta_AIC"
  )

ggplot(aic_long,
       aes(x = tokens_seen_numeric,
           y = delta_AIC,
           color = predictor)) +
  geom_line() +
  geom_hline(yintercept = 0, linetype = "dotted") +
  scale_x_log10() +
  labs(
    y = expression(Delta*AIC ~ "(vs null)"),
    x = "Tokens seen",
    color = "Predictor"
  ) +
  theme_minimal(base_size = 14)
```

