## Compute information scores for attention heads, over False Belief passage regions of interest

## Goal: Generating a Tensor A with dimensions corresponding to the number of models, steps, layers, heads, passages, and rois? Where the values contained in Tensor A correspond to the max attention head scores for the corresponding region of interest. 
## And similarly, make a Tensor B with the same number and type of dimensions, but containing values representing the length of the region of interest as a fraction over the entire length of the tokenized passage? 

# prompt for Claude: 
#
# hello! I am in Python, and I have a dataframe with columns: `model_shorthand`, `step`, `layer`, `head`, `tokenized_passage`, and max attention scores for each of five regions of interest within this tokenized passage: `attn_max_setup_indices, attn_max_exit_indices, attn_max_manipulation_indices attn_max_return_indices, attn_max_query_indices`. I also have the corresponding token indices that map onto each passage, for each region of interest: setup_indices', 'exit_indices', 'manipulation_indices', 'return_indices', 'query_indices', which contain tuples (start_index, end_index), inclusive of end index. What is the most efficient way of generating a Tensor A with dimensions corresponding to the number of models, steps, layers, heads, passages, and rois? Where the values contained in Tensor A correspond to the max attention head scores for the corresponding region of interest. And similarly, what is the best way to make a Tensor B with the same number and type of dimensions, but containing values representing the length of the region of interest as a fraction over the entire length of the tokenized passage?

import ast
import os

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from itertools import product
from tqdm import tqdm

# Define a function that cleans up the attention scores (which for some reason are interpreted as strings rather than numpy arrays or lists)
def parse_attention_string(s):
    """
    Convert a stringified numpy array to a 1D numpy array.
    """
    if isinstance(s, np.ndarray):
        return s
    if isinstance(s, list):
        return np.asarray(s)
    return np.fromstring(s.strip("[]"), sep=" ")

# Define a function to clean up the roi tuple entries (which also look like strings)
import ast
import numpy as np

def parse_roi_span_string(x):
    """
    Parse an ROI span stored as a string into a (start, end) tuple.

    Returns:
        (start, end) tuple, or None if missing / invalid
    """
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return None
    # Already parsed
    if isinstance(x, tuple):
        return x
    if isinstance(x, str):
        parsed = ast.literal_eval(x)
        if isinstance(parsed, tuple) and len(parsed) == 2:
            return parsed
    return None


def info_score(roi_score_mat,p_roi): 

	"""
		Compute information scores for a given attention head.

		Args: 
			roi_score_mat: matrix with 
				rows: passages, 
				cols: regions of interest; 
				vals: max attention score
			p_roi_mat: matrix with
				rows: passages,
				cols: regions of interest;
				vals: probability of roi "occupancy"--should be a function of 
				the number of tokens that make up a given ROI span, as they are not equally sized

		Returns: 
			information score

	"""

	for (attn_scores, p_occupancies) in zip(roi_score_mat,p_roi_mat):
		
		F_by_conditions = np.mean(roi_score_mat, 0)
		F_mean = np.mean(row)
		info = 0
		for F_i,p_i in zip(attn_scores,p_occupancies):
			info += p_i*(F_i/F_mean) * np.log2(F_i/F_mean)

	return info

def shuffle_distribution_test(k_shuffles=1000):

	"""
		Test any given information score for its likelihood of having been generated by chance. 
		Create a distribution of shuffles (roi-attention shuffles), hold probability of occupancy. 

	"""

datapath = "../../data/processed/aggregated_attn_rois/"
files = os.listdir(datapath)
olmo_files = [f for f in files if "OLMo" in f] # filter for Olmo in case other models are here 

df = pd.read_csv(os.path.join(datapath,olmo_files[0]))

unique_model_step_layer_heads = df.groupby(["model_shorthand","step","layer","head"]).count()
unique_layers = set(unique_model_step_layer_heads["layer"].tolist())
unique_heads = set(unique_model_step_layer_heads["head"].tolist())
layer_heads = list(product(unique_layers,unique_heads))

n_passages = len(set(df["passage"].tolist()))
n_rois = 5
for layer, head in layer_heads:
	sublayerhead = df[(df["layer"] == layer) & (df["head"] == head)].reset_index()

	p_roi = np.zeros((n_passages,n_rois))
	max_attns = np.zeros((n_passages,n_rois))
	for i,row in tqdm(sublayerhead.iterrows(),total=sublayerhead.shape[0]):
		mname = row["model_shorthand"]
		step = row["step"]
		tokens_seen = row["tokens_seen"]
		passage = row["passage"]
		tokenized_passage = ast.literal_eval(row["tokenized_passage"])
		## Compute probabilities of "occupancy" e.g. fraction of tokens roi occupies in passage
		n_tokens_passage = len(tokenized_passage)
		n_tokens_setup = ast.literal_eval(row["setup_indices"])[1] - ast.literal_eval(row["setup_indices"])[0] # n tokens for setup
		n_tokens_exit = ast.literal_eval(row["exit_indices"])[1] - ast.literal_eval(row["exit_indices"])[0]# n tokens for exit
		n_tokens_manipulation = ast.literal_eval(row["manipulation_indices"])[1] - ast.literal_eval(row["manipulation_indices"])[0]# n tokens for manipulation
		n_tokens_return = ast.literal_eval(row["return_indices"])[1] - ast.literal_eval(row["return_indices"])[0]# n tokens for return
		n_tokens_query = ast.literal_eval(row["query_indices"])[1] - ast.literal_eval(row["query_indices"])[0]# n tokens for query
		# create an array of probabilities of occupancy
		n_roi = np.hstack((n_tokens_setup, n_tokens_exit, n_tokens_manipulation, n_tokens_return, n_tokens_query))
		p_roi[i,:] = n_roi/n_tokens_passage
		## Arrange the maximum attention scores per roi in a numpy array
		max_setup = row["attn_max_setup_indices"]
		max_exit = row["attn_max_exit_indices"]
		max_manipulation = row["attn_max_manipulation_indices"]
		max_return = row["attn_max_return_indices"]
		max_query = row["attn_max_query_indices"]
		## Add these as a new row in a matrix of passages x attention scores
		max_attns[i,:] = np.hstack((max_setup, max_exit, max_manipulation, max_return, max_query))

	## Now that you have the matrix, compute the information score


